// <auto-generated />
using System;
using DatnekLingua_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatnekLingua_API.Data.Migrations
{
    [DbContext(typeof(LanguagesDbContext))]
    [Migration("20210504182412_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DatnekLingua_API.Data.Models.Language", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<bool>("IsCompulsoryToTheApplication");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Guid");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DatnekLingua_API.Data.Models.NiveauComprehension", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Guid");

                    b.ToTable("NiveauxComprehensions");
                });

            modelBuilder.Entity("DatnekLingua_API.Data.Models.NiveauEcrit", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Guid");

                    b.ToTable("NiveauxEcrits");
                });

            modelBuilder.Entity("DatnekLingua_API.Data.Models.NiveauParle", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Guid");

                    b.ToTable("NiveauxParles");
                });

            modelBuilder.Entity("DatnekLingua_API.Data.Models.UserConfiguredLanguage", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<bool>("IsApplicationUserLanguage");

                    b.Property<Guid>("LanguageGuid");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<Guid>("NiveauComprehensionGuid");

                    b.Property<Guid>("NiveauEcritGuid");

                    b.Property<Guid>("NiveauParleGuid");

                    b.HasKey("Guid");

                    b.HasIndex("LanguageGuid");

                    b.HasIndex("NiveauComprehensionGuid");

                    b.HasIndex("NiveauEcritGuid");

                    b.HasIndex("NiveauParleGuid");

                    b.ToTable("UserConfiguredLanguages");
                });

            modelBuilder.Entity("DatnekLingua_API.Data.Models.UserConfiguredLanguage", b =>
                {
                    b.HasOne("DatnekLingua_API.Data.Models.Language", "LanguageConcerned")
                        .WithMany("UserConfiguredLanguagesConcerned")
                        .HasForeignKey("LanguageGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DatnekLingua_API.Data.Models.NiveauComprehension", "NiveauComprehension")
                        .WithMany("LanguagesConcerned")
                        .HasForeignKey("NiveauComprehensionGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DatnekLingua_API.Data.Models.NiveauEcrit", "NiveauEcrit")
                        .WithMany("LanguagesConcerned")
                        .HasForeignKey("NiveauEcritGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DatnekLingua_API.Data.Models.NiveauParle", "NiveauParle")
                        .WithMany("LanguagesConcerned")
                        .HasForeignKey("NiveauParleGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
